from os import environ

DATABASE_HOST = environ["DATABASE_HOST"]
DATABASE_PORT = environ["DATABASE_PORT"]
DATABASE_DB = environ["DATABASE_DB"]
VALID_HYPHENATIONS_COLLECTION = environ["VALID_HYPHENATIONS_COLLECTION"]
INVALID_HYPHENATIONS_COLLECTION = environ["INVALID_HYPHENATIONS_COLLECTION"]
TAGGER_NAME = environ["TAGGER_NAME"]
HYPHENATED_CLASSIFIER_NAME = environ["HYPHENATED_CLASSIFIER_NAME"]