from os import environ

DATABASE_HOST = environ["DATABASE_HOST"]
DATABASE_PORT = environ["DATABASE_PORT"]
DATABASE_DB = environ["DATABASE_DB"]
VOCABULARY_COLLECTION = environ["VOCABULARY_COLLECTION"]
DICTIONARY_COLLECTION = environ["DICTIONARY_COLLECTION"]
USER_DICTIONARY_COLLECTION = environ["USER_DICTIONARY_COLLECTION"]
TAGGER_NAME = environ["TAGGER_NAME"]
HYPHENATED_CLASSIFIER_NAME = environ["HYPHENATED_CLASSIFIER"]
RAW_COLLECTION = environ["RAW_COLLECTION"]
TOKENIZED_COLLECTION = environ["TOKENIZED_COLLECTION"]